backend:
  name: git-gateway
  branch: main
media_folder: "aktualne/fotos"
collections:
  - name: "aktualne"
    label: "Aktuálně"
    folder: "aktualne"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/aktuality.njk"}
      - {label: "Tags", name: "tags", widget: "hidden", default: "news"}
      - {label: "Název", name: "title", widget: "string"}
      - {label: "Datum publikace", name: "date", widget: "datetime"}
      - {label: "Termín", name: "term", widget: "string"}
      - {label: "Popis", name: "perex", widget: "string"}
      - {label: "Obsah", name: "body", widget: "markdown"}
      - {label: "Fotka", name: "foto", widget: "image", required: false}

